package io.inji.verify.enums;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum ErrorCode {
    INVALID_TRANSACTION_ID("INVALID_TRANSACTION_ID","Invalid transaction ID, No requests found for given transaction ID."),
    NO_VP_SUBMISSION("NO_VP_SUBMISSION","No VP submission found for given transaction ID."),
    NO_AUTH_REQUEST("NO_AUTH_REQUEST","No Authorization request found for given request ID."),
    BOTH_ID_AND_PD_CANNOT_BE_NULL("BOTH_ID_AND_PD_CANNOT_BE_NULL","Both Presentation Definition and Presentation Definition ID cannot be empty."),
    NO_PRESENTATION_DEFINITION("NO_PRESENTATION_DEFINITION","No Presentation Definition found for given Presentation Definition ID."),
    DCQL_QUERY_REQUIRED("dcql_query_required","dcql_query is required"),
    DCQL_QUERY_INVALID( "dcql_query_invalid","dcql_query is invalid"),
    AMBIGUOUS_QUERY("ambiguous_query","Both dcql_query and presentationDefinition provided"),
    INVALID_REQUEST_FORMAT("invalid_request_format", "Request body JSON is invalid or cannot be parsed."),
    DCQL_VALIDATION_ERROR("dcql_validation_error","DCQL structure invalid"),
    DCQL_CREDENTIALS_REQUIRED("dcql_query.credentials","Each DCQL credential entry must not be null."),
    DCQL_CREDENTIALS_INVALID("dcql_query.credentials","dcql_query.credentials must be a non-empty array."),
    DCQL_CREDENTIAL_ID_REQUIRED("dcql_query.credentials","Each DCQL credential entry must contain id."),
    DCQL_CREDENTIAL_ID_INVALID("dcql_query.credentials","Credential id must contain only alphanumeric characters, underscores, and hyphens."),
    DCQL_DUPLICATE_CREDENTIAL_ID("dcql_query.credentials","Credential ids must be unique within the DCQL query."),
    DCQL_CREDENTIAL_FORMAT_REQUIRED("dcql_query.credentials","Each DCQL credential entry must contain format."),
    DCQL_CREDENTIAL_FORMAT_INVALID("dcql_query.credentials","DCQL credential format must be a valid format."),
    DCQL_CREDENTIAL_FORMAT_UNSUPPORTED("dcql_query.credentials","Unsupported DCQL credential format."),
    DCQL_META_REQUIRED("dcql_query.credentials","Each DCQL credential entry must contain meta."),
    DCQL_META_INVALID("dcql_query.credentials","DCQL credential meta must be a valid meta."),
    DCQL_DOCTYPE_VALUE_REQUIRED("dcql_query.credentials","mso_mdoc credentials must contain meta.doctype_value."),
    INVALID_META_STRUCTURE("dcql_validation_error","dcql_query.credentials[].meta must contain valid format-specific constraints."),
    INVALID_TRUSTED_AUTHORITIES_STRUCTURE("dcql_validation_error","dcql_query.credentials[].trusted_authorities must contain valid authority filters."),
    DCQL_CLAIM_ID_REQUIRED("dcql_validation_error","Each claim must contain id when claim_sets is used."),
    DCQL_CLAIM_PATH_REQUIRED("dcql_query.credentials","Each claim must contain path."),
    DCQL_CREDENTIAL_SETS_REQUIRED("dcql_query.credentials","Each DCQL credential entry must contain credential_sets."),
    DCQL_CLAIM_PATH_INVALID("dcql_query.credentials","DCQL claim path must be a valid path."),
    INVALID_CLAIM_SETS_STRUCTURE("dcql_validation_error","dcql_query.credentials[].claim_sets must contain valid claim id combinations."),
    INVALID_CREDENTIAL_SETS_STRUCTURE("dcql_validation_error","dcql_query.credential_sets must contain valid credential id combinations."),
    PRESENTATION_DEFINITION_NOT_SUPPORTED("presentation_definition","presentation_definition is not supported"),
    INVALID_CLAIMS_STRUCTURE("dcql_validation_error","dcql_query.credentials[].claims must contain valid claim path definitions."),
    CLIENT_ID_REQUIRED("invalid_request","client_id is required"),
    DID_CREATION_FAILED("DID_CREATION_FAILED","Error while creating DID document."),
    VP_SUBMISSION_EXCEPTION("VP_SUBMISSION_EXCEPTION","Error while processing VP submission"),
    TOKEN_MATCHING_FAILED("TOKEN_MATCHING_FAILED", "Token matching failed."),
    INVALID_VP_TOKEN("INVALID_VP_TOKEN","Verifiable presentation failed due to invalid VP token"),
    VP_WITHOUT_PROOF("VP_WITHOUT_PROOF", "Invalid VP Submission since VP is without proof"),
    RESPONSE_CODE_NOT_MATCHING("RESPONSE_CODE_NOT_MATCHING", "Response code is not matching the VP Submission response"),
    RESPONSE_CODE_EXPIRED("RESPONSE_CODE_EXPIRED", "Response code has expired"),
    RESPONSE_CODE_USED("RESPONSE_CODE_USED", "Response code has been used"),
    RESPONSE_CODE_NOT_FOUND("RESPONSE_CODE_NOT_FOUND", "Response code is missing for this VP Submission"),
    REDIRECT_URI_NOT_FOUND("REDIRECT_URI_NOT_FOUND", "Redirect URI configuration is missing"),
    VP_SESSION_INVALID("VP_SESSION_INVALID", "Your VP verification session is invalid. Please restart the process and try again"),
    MALFORMED_COOKIE("MALFORMED_COOKIE", "Request cannot be processed due to malformed cookie" ),
    RESPONSE_CODE_NOT_USED("RESPONSE_CODE_NOT_USED", "Transaction was incomplete, response_code was not used" ),
    NONCE_VALIDATION_FAILED("invalid_request", "Nonce validation failed due to invalid nonce"),
    CLIENT_ID_VALIDATION_FAILED("invalid_request", "Client id validation failed due to invalid client id"),
    CLIENT_ID_NONCE_VALIDATION_FAILED("invalid_request", "Client id or nonce validation failed"),
    VP_VERIFICATION_FAILED("VP_VERIFICATION_FAILED", "VP verification failed due to runtime exception during VP verification"),
    INVALID_STATE_MISSING("invalid_request", "State parameter is required and cannot be empty."),
    NO_MATCHING_VP_REQUEST("invalid_request", "Invalid state parameter: No matching VP request found."),
    VP_REQUEST_EXPIRED("invalid_request", "Invalid state parameter: VP request has expired."),
    VP_ALREADY_SUBMITTED("invalid_request", "VP response has already been submitted."),
    EITHER_VP_TOKEN_OR_ERROR_REQUIRED("invalid_request", "Either vp_token or error must be provided."),
    BOTH_VP_TOKEN_AND_ERROR_NOT_ALLOWED("invalid_request", "Both vp_token and error cannot be provided together."),
    ERROR_DESCRIPTION_VP_TOKEN_CONFLICT("invalid_request", "If error_description is provided, vp_token must be null."),
    ERROR_DESCRIPTION_ERROR_REQUIRED("invalid_request", "If error_description is provided, error must also be provided."),
    VP_TOKEN_REQUIRED("invalid_request", "invalid_vp_token: vp_token is required and cannot be empty or 'null'"),
    DUPLICATE_QUERY_IDS_NOT_ALLOWED("invalid_request", "invalid_vp_token: duplicate query ids are not allowed"),
    VP_TOKEN_MUST_HAVE_KEY_VALUE_PAIR("invalid_request", "invalid_vp_token: must contain at least one key-value pair"),
    VP_TOKEN_VALUES_MUST_BE_ARRAYS("invalid_request", "invalid_vp_token: all values must be arrays"),
    VP_TOKEN_ARRAYS_MUST_HAVE_ELEMENTS("invalid_request", "invalid_vp_token: all arrays must have at least one element"),
    VP_TOKEN_ARRAY_ELEMENTS_INVALID("invalid_request", "invalid_vp_token: array elements must be non-empty JSON objects or non-empty SD-JWT strings"),
    VP_TOKEN_ALL_ELEMENTS_MUST_BE_OBJECTS("invalid_request", "invalid_vp_token: all elements must be non-empty JSON objects"),
    VP_TOKEN_ALL_ELEMENTS_MUST_BE_SD_JWT("invalid_request", "invalid_vp_token: all elements must be non-empty SD-JWT strings"),
    VP_TOKEN_NOT_VALID_JSON_OBJECT("invalid_request", "invalid_vp_token, not a valid JSON object"),
    INTERNAL_SERVER_ERROR("internal_server_error", "Internal server error");

    private final String errorCode;
    private final String errorMessage;
}